module.exports={
 ci:{
  collect:{
   url:[
    'http://127.0.0.1:4173/',
    'http://127.0.0.1:4173/tools',
    'http://127.0.0.1:4173/tools/take-home-pay',
    'http://127.0.0.1:4173/tools/screenshot-beautifier'
   ],
   startServerCommand:'npm run preview -- --host 127.0.0.1 --port 4173',
   startServerReadyPattern:'Local:',
   numberOfRuns:1
  },
  assert:{
   assertions:{
    'categories:performance':['warn',{minScore:0.70}],
    'categories:accessibility':['error',{minScore:0.90}],
    'categories:best-practices':['error',{minScore:0.90}],
    'categories:seo':['error',{minScore:0.90}],
    'largest-contentful-paint':['warn',{maxNumericValue:4000}],
    'cumulative-layout-shift':['error',{maxNumericValue:0.25}],
    'total-blocking-time':['warn',{maxNumericValue:600}]
   }
  },
  upload:{target:'temporary-public-storage'}
 }
}
