import Seo from '../components/Seo'
import { officialSources } from '../data/officialSources'
import { useI18n } from '../i18n'

export default function Methodology(){
 const {lang}=useI18n()
 const c={
  en:{title:'Methodology & data quality',desc:'How AnyTool verifies calculator rules, official sources, AI outputs and government data.',intro:'AnyTool separates deterministic calculations from AI tasks. Formula-based tools are implemented in JavaScript and regression-tested. Regulated Taiwan tools carry source references and verification dates. AI is not used to invent statutory rates.',sourceTitle:'Current high-priority sources',cards:[['Deterministic first','Tax, insurance, salary and percentage math stays in code and is covered by regression tests.'],['Official-source grounding','Government pages and open data are preferred over blogs or secondary summaries.'],['Freshness monitoring','A scheduled source monitor checks high-value official pages and flags changes for review instead of silently changing formulas.'],['AI with fallback','OCR and extraction can route across multiple configured providers; the UI shows the provider used.'],['Human-readable evidence','Important regulated tools display source authority, last-verified date and limitations next to the result.'],['No fake precision','When a government source exposes approved beds but not live vacancies, AnyTool labels it as approved capacity rather than claiming it is available.']]},
  'zh-TW':{title:'方法與資料品質',desc:'了解 AnyTool 如何查核計算規則、官方來源、AI 輸出與政府公開資料。',intro:'AnyTool 將可確定的公式計算與 AI 任務分開。公式工具以 JavaScript 實作並做回歸測試；涉及台灣法規與公共服務的工具會顯示官方來源與查核日期。AI 不用來猜測法定費率。',sourceTitle:'目前優先查核的官方來源',cards:[['公式優先','稅務、保險、薪資與百分比計算保留在程式公式中，並以回歸測試驗證。'],['官方來源','優先採用主管機關頁面與政府開放資料，而不是部落格或二手整理。'],['新鮮度監控','排程來源監控器會檢查重要官方頁面，若內容變動就標記人工審查，不會靜默改公式。'],['AI 備援','OCR 與結構化擷取可在多個已設定供應商間切換，介面會顯示實際使用的供應商。'],['可讀證據','重要法規工具會在結果旁顯示主管機關、最後查核日期與限制。'],['不製造假精確','若政府資料只有核定床位而非即時空床，AnyTool 會明確標示核定容量，不會聲稱是可入住床位。']]},
  ar:{title:'المنهجية وجودة البيانات',desc:'كيف يتحقق AnyTool من قواعد الحاسبات والمصادر الرسمية ومخرجات الذكاء الاصطناعي والبيانات الحكومية.',intro:'يفصل AnyTool الحسابات الحتمية عن مهام الذكاء الاصطناعي. تُنفذ أدوات الصيغ في JavaScript وتخضع لاختبارات رجعية. أدوات تايوان التنظيمية تعرض مصادرها الرسمية وتاريخ التحقق. لا نستخدم AI لاختراع معدلات قانونية.',sourceTitle:'المصادر الرسمية ذات الأولوية',cards:[['الحساب الحتمي أولاً','تبقى حسابات الضرائب والتأمين والرواتب والنسب في الشيفرة وتخضع لاختبارات رجعية.'],['الاعتماد على المصادر الرسمية','نفضل صفحات الحكومة والبيانات المفتوحة على المدونات أو الملخصات الثانوية.'],['مراقبة التحديثات','يفحص مراقب مجدول الصفحات الرسمية المهمة ويطلب مراجعة عند التغيير بدلاً من تعديل الصيغ بصمت.'],['AI مع بدائل','يمكن لـ OCR والاستخراج الانتقال بين مزودين متعددين وتعرض الواجهة المزود المستخدم.'],['دليل مفهوم','تعرض الأدوات التنظيمية المهمة الجهة الرسمية وتاريخ آخر تحقق والقيود بجانب النتيجة.'],['لا دقة زائفة','إذا نشرت الحكومة سعة معتمدة فقط دون شواغر حية، نعرضها كسعة معتمدة ولا نسميها أسرة متاحة.']]},
  ur:{title:'طریقۂ کار اور ڈیٹا معیار',desc:'AnyTool کیلکولیٹر قواعد، سرکاری ذرائع، AI نتائج اور حکومتی ڈیٹا کی تصدیق کیسے کرتا ہے۔',intro:'AnyTool یقینی فارمولہ حسابات کو AI کاموں سے الگ رکھتا ہے۔ فارمولہ ٹولز JavaScript میں ہیں اور regression tests سے چیک ہوتے ہیں۔ تائیوان کے قانونی ٹولز سرکاری ماخذ اور آخری تصدیق کی تاریخ دکھاتے ہیں۔ AI قانونی شرحیں گھڑنے کے لیے استعمال نہیں ہوتا۔',sourceTitle:'اہم موجودہ سرکاری ذرائع',cards:[['یقینی حساب پہلے','ٹیکس، انشورنس، تنخواہ اور فیصد کا حساب کوڈ میں رہتا ہے اور regression tests سے چیک ہوتا ہے۔'],['سرکاری ماخذ کی بنیاد','بلاگ یا ثانوی خلاصوں کے بجائے سرکاری صفحات اور اوپن ڈیٹا کو ترجیح دی جاتی ہے۔'],['تازگی کی نگرانی','شیڈول مانیٹر اہم سرکاری صفحات دیکھتا ہے اور تبدیلی پر review flag کرتا ہے، فارمولا خاموشی سے نہیں بدلتا۔'],['AI بیک اپ','OCR اور extraction کئی providers کے درمیان روٹ ہو سکتے ہیں اور UI استعمال شدہ provider دکھاتا ہے۔'],['واضح ثبوت','اہم قانونی ٹولز نتیجے کے ساتھ سرکاری ادارہ، تصدیق کی تاریخ اور حدود دکھاتے ہیں۔'],['جعلی درستگی نہیں','اگر سرکاری ڈیٹا صرف منظور شدہ بیڈ بتاتا ہے، live vacancy نہیں، تو AnyTool اسے capacity ہی کہتا ہے۔']]}
 }[lang]||null
 const x=c||{}
 return <section className="mx-auto max-w-5xl px-4 py-16"><Seo title={(x.title||'Methodology')+' | AnyTool.online'} description={x.desc||''}/><h1 className="text-4xl font-black">{x.title}</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-300">{x.intro}</p><div className="mt-10 grid gap-4 md:grid-cols-2">{x.cards.map(([h,p])=><article className="card p-5" key={h}><h2 className="font-bold">{h}</h2><p className="mt-2 text-sm leading-6 text-slate-400">{p}</p></article>)}</div><h2 className="mt-12 text-2xl font-black">{x.sourceTitle}</h2><div className="mt-4 grid gap-3">{Object.values(officialSources).slice(0,8).map(s=><a key={s.url} href={s.url} target="_blank" rel="noreferrer" className="card p-4 hover:border-emerald-400/30"><strong>{s.title}</strong><p className="mt-1 text-sm text-slate-400">{s.authority} · {s.verified}</p></a>)}</div></section>
}
