import { useEffect, useState } from 'react'
import { Pause, Play, RefreshCw, RotateCcw, Trash2 } from 'lucide-react'

const Field=({label,children})=><label className="block"><span className="mb-1.5 block text-sm font-semibold text-slate-400">{label}</span>{children}</label>
const Action=({children,onClick,primary=false})=><button type="button" onClick={onClick} className={primary?'btn-primary':'btn-ghost'}>{children}</button>
const Stat=({label,value})=><div className="result-tile"><div className="text-xs text-slate-500">{label}</div><div className="mt-1 break-words text-lg font-black">{value}</div></div>

export function Pomodoro(){
 const [work,setWork]=useState(25),[short,setShort]=useState(5),[long,setLong]=useState(15),[mode,setMode]=useState('work'),[left,setLeft]=useState(25*60),[running,setRunning]=useState(false),[sessions,setSessions]=useState(0),[task,setTask]=useState(''),[tasks,setTasks]=useState(()=>{try{return JSON.parse(localStorage.getItem('anytool_pomodoro_tasks')||'[]')}catch{return []}})
 const mins=mode==='work'?work:mode==='short'?short:long,total=Math.max(1,Math.round(mins*60))
 useEffect(()=>{if(!running)setLeft(total)},[work,short,long,mode,total,running])
 useEffect(()=>{if(!running)return;const id=setInterval(()=>setLeft(v=>{if(v<=1){setRunning(false);if(mode==='work')setSessions(s=>s+1);return total}return v-1}),1000);return()=>clearInterval(id)},[running,mode,total])
 const save=xs=>{setTasks(xs);try{localStorage.setItem('anytool_pomodoro_tasks',JSON.stringify(xs))}catch{}}
 const add=()=>{if(task.trim()){save([...tasks,{id:Date.now(),text:task.trim(),done:false}]);setTask('')}}
 const time=String(Math.floor(left/60)).padStart(2,'0')+':'+String(left%60).padStart(2,'0')
 return <div className="tool-work-grid"><section className="tool-control-panel space-y-4"><div className="segmented-control"><button className={mode==='work'?'active':''} onClick={()=>{setRunning(false);setMode('work')}}>Focus</button><button className={mode==='short'?'active':''} onClick={()=>{setRunning(false);setMode('short')}}>Short break</button><button className={mode==='long'?'active':''} onClick={()=>{setRunning(false);setMode('long')}}>Long break</button></div><div className="grid gap-3 sm:grid-cols-3"><Field label="Focus minutes"><input aria-label="Focus minutes" className="input" type="number" min="1" max="120" value={work} onChange={e=>setWork(Number(e.target.value))}/></Field><Field label="Short break"><input className="input" type="number" min="1" max="60" value={short} onChange={e=>setShort(Number(e.target.value))}/></Field><Field label="Long break"><input className="input" type="number" min="1" max="90" value={long} onChange={e=>setLong(Number(e.target.value))}/></Field></div><div className="text-center"><div aria-label="Pomodoro time" className="text-6xl font-black tracking-tight">{time}</div><div className="mt-2 text-sm text-slate-500">Completed focus sessions: {sessions}</div><div className="mt-5 flex justify-center gap-2"><Action primary onClick={()=>setRunning(v=>!v)}>{running?<><Pause size={16}/> Pause</>:<><Play size={16}/> Start</>}</Action><Action onClick={()=>{setRunning(false);setLeft(total)}}><RotateCcw size={16}/> Reset</Action></div></div></section><section className="tool-result-panel"><h3 className="font-bold">Focus tasks</h3><div className="mt-3 flex gap-2"><input aria-label="Pomodoro task" className="input" value={task} onChange={e=>setTask(e.target.value)} onKeyDown={e=>e.key==='Enter'&&add()} placeholder="Add a task…"/><Action onClick={add}>Add</Action></div><div className="mt-4 grid gap-2">{tasks.map(t=><div key={t.id} className="flex items-center gap-2 rounded-xl border border-white/[0.06] p-3"><input type="checkbox" checked={t.done} onChange={()=>save(tasks.map(x=>x.id===t.id?{...x,done:!x.done}:x))}/><span className={'flex-1 '+(t.done?'line-through text-slate-500':'')}>{t.text}</span><button aria-label={'Delete '+t.text} onClick={()=>save(tasks.filter(x=>x.id!==t.id))} className="text-slate-500 hover:text-rose-300"><Trash2 size={15}/></button></div>)}</div></section></div>
}

const zones=[['Taipei','Asia/Taipei'],['Tokyo','Asia/Tokyo'],['Singapore','Asia/Singapore'],['London','Europe/London'],['Zurich','Europe/Zurich'],['New York','America/New_York'],['Los Angeles','America/Los_Angeles'],['Sydney','Australia/Sydney'],['Dubai','Asia/Dubai']]
export function WorldClock(){
 const [now,setNow]=useState(new Date()),[selected,setSelected]=useState(['Asia/Taipei','Asia/Tokyo','Europe/London','America/New_York']),[add,setAdd]=useState('Asia/Singapore')
 useEffect(()=>{const id=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(id)},[])
 const fmt=(zone,opt)=>new Intl.DateTimeFormat(undefined,{timeZone:zone,...opt}).format(now)
 const addZone=()=>setSelected(s=>s.includes(add)?s:[...s,add])
 return <div className="space-y-4"><div className="card flex flex-wrap items-end gap-3 p-5"><Field label="Add city"><select aria-label="Add world clock city" className="input min-w-52" value={add} onChange={e=>setAdd(e.target.value)}>{zones.map(([n,z])=><option key={z} value={z}>{n}</option>)}</select></Field><Action primary onClick={addZone}>Add clock</Action></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{selected.map(zone=>{const name=zones.find(x=>x[1]===zone)?.[0]||zone;return <div key={zone} className="card p-5"><div className="flex justify-between"><div><div className="text-xs font-black uppercase tracking-[.14em] text-slate-500">{zone}</div><h3 className="mt-1 text-xl font-black">{name}</h3></div><button aria-label={'Remove '+name} onClick={()=>setSelected(s=>s.filter(x=>x!==zone))} className="text-slate-500 hover:text-rose-300"><Trash2 size={16}/></button></div><div className="mt-5 text-4xl font-black tabular-nums">{fmt(zone,{hour:'2-digit',minute:'2-digit',second:'2-digit'})}</div><div className="mt-2 text-sm text-slate-400">{fmt(zone,{weekday:'long',year:'numeric',month:'short',day:'numeric'})}</div></div>})}</div></div>
}

const prompt='the quick brown fox jumps over the lazy dog while modern tools help people work faster with clear simple reliable results'
export function TypingTest(){
 const [duration,setDuration]=useState(60),[typed,setTyped]=useState(''),[started,setStarted]=useState(false),[timeLeft,setTimeLeft]=useState(60),[finished,setFinished]=useState(false)
 useEffect(()=>{setTimeLeft(duration);setTyped('');setStarted(false);setFinished(false)},[duration])
 useEffect(()=>{if(!started||finished)return;const id=setInterval(()=>setTimeLeft(v=>{if(v<=1){setFinished(true);setStarted(false);return 0}return v-1}),1000);return()=>clearInterval(id)},[started,finished])
 const elapsed=Math.max(1,duration-timeLeft),correct=[...typed].filter((c,i)=>c===prompt[i]).length,accuracy=typed.length?Math.round(correct/typed.length*100):100,wpm=Math.round((correct/5)/(elapsed/60)),wordsCorrect=typed.trim()?typed.trim().split(/\s+/).filter((w,i)=>w===prompt.split(' ')[i]).length:0
 const reset=()=>{setTyped('');setTimeLeft(duration);setStarted(false);setFinished(false)}
 return <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-4"><Stat label="WPM" value={wpm}/><Stat label="Accuracy" value={accuracy+'%'}/><Stat label="Correct words" value={wordsCorrect}/><Stat label="Time left" value={timeLeft+'s'}/></div><div className="card p-5 space-y-4"><div className="flex flex-wrap items-end justify-between gap-3"><Field label="Duration"><select aria-label="Typing duration" className="input" value={duration} onChange={e=>setDuration(Number(e.target.value))}><option value="30">30 seconds</option><option value="60">60 seconds</option><option value="120">120 seconds</option></select></Field><Action onClick={reset}><RefreshCw size={15}/> New test</Action></div><div aria-label="Typing prompt" className="rounded-2xl border border-white/[0.07] bg-slate-950/70 p-5 text-lg leading-8 tracking-wide text-slate-300">{prompt}</div><Field label="Type the text"><textarea aria-label="Typing input" autoFocus disabled={finished} className="input min-h-36" value={typed} onChange={e=>{if(!started&&!finished)setStarted(true);setTyped(e.target.value.slice(0,prompt.length))}} placeholder="Start typing here…"/></Field>{finished&&<p className="status-message text-emerald-300">Test complete. Reset to try again.</p>}</div></div>
}
